
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-7pm-3
owner: ucsb-cs156-s23
repo_name: team03-s23-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NDA1OTEx","is_bot":false,"login":"wq12li","name":""},"headRefName":"Kenny-IceCreamShopConnection","number":26,"title":"Link frontend and backend for IceCreamShops","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-3/pull/26"},{"author":{"id":"MDQ6VXNlcjg2NzQ4NzMx","is_bot":false,"login":"nagpalishaan","name":""},"headRefName":"Ishaan-IceCreamShopFixPlurality","number":25,"title":"Change icecreamshop to be icecreamshops for api","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-3/pull/25"}]
